---
output:
  pdf_document: default
  html_document: default
---

# Rapport d'Analyse de Données

## Introduction
Ce rapport documente l'analyse approfondie des données de l'Indice de Développement Humain (IDH) collectées. L'objectif est de comprendre les tendances de développement humain à travers différents pays et régions du monde sur une période de temps donnée, allant de 1960 à 2021. Nous utiliserons diverses techniques de nettoyage, transformation et visualisation de données pour explorer ces informations de manière exhaustive.

## Auteurs 
- El Kbabty Mouad
- Essouaid Khalil

## Description du Jeu de Données

### Source des Données
- **Nom du jeu de données**: Indice de Développement Humain (IDH)
- **Source**: [UNDP](https://mavenanalytics.io/data-playground)
- **Date de collecte**: 2024

### Contenu des Données
- **Nombre de lignes**: 189 (pays)
- **Nombre de colonnes**: Plusieurs colonnes couvrant diverses années et indicateurs
- **Aperçu des colonnes**:
  - `iso3`: Code ISO 3 lettres du pays
  - `country`: Nom du pays
  - `hdicode`: Catégorie de l'IDH (Low, Medium, High, Very High)
  - `region`: Région géographique
  - `hdi_rank_2021`: Rang de l'IDH en 2021
  - `hdi_1990` à `hdi_2000`: Valeurs de l'IDH pour chaque année de 1990 à 2000
  - `le_1990`: Espérance de vie en 1990
  - `le_m_1990`: Espérance de vie pour les hommes en 1990
  - `le_f_1990`: Espérance de vie pour les femmes en 1990
  - `le_pc_1990`: Variation en pourcentage de l'espérance de vie en 1990
  - `mf_1990`: Ratio hommes-femmes en 1990
  - `phdi_1990`: Indice potentiel de développement humain en 1990
  - `eys_1990`: Années de scolarisation attendues en 1990
  - `mys_1990`: Nombre moyen d'années de scolarisation en 1990
  - `gnipc_1990`: Revenu national brut par habitant en 1990
  - `gdi_1990`: Indice de développement lié au genre en 1990
  
## Variables d'Intérêt

### Variables Qualitatives
- **hdicode** (Catégorie de l'IDH)
  - Description: Cette variable indique la catégorie de l'Indice de Développement Humain (IDH) du pays.
  - Modalités:
    - Low: Pays à faible IDH
    - Medium: Pays à IDH moyen
    - High: Pays à IDH élevé
    - Very High: Pays à IDH très élevé
  - Données manquantes: Si présentes, elles indiqueront que l'IDH de ce pays n'est pas catégorisé.

- **region** (Région géographique)
  - Description: Cette variable représente la région géographique où se trouve le pays.
  - Modalités:
    - SA: Asie du Sud
    - SSA: Afrique subsaharienne
    - ECA: Europe et Asie centrale
    - AS: Asie
    - (Autres modalités possibles correspondant à d'autres régions)
  - Données manquantes: Indiqueront qu'aucune région géographique n'est attribuée au pays.

### Variables Quantitatives
- **hdi_2021** (IDH en 2021)
  - Description: Cette variable représente l'Indice de Développement Humain pour l'année 2021.
  - Unité de mesure: L'IDH est un nombre décimal entre 0 et 1, où 0 représente un développement humain très faible et 1 un développement humain très élevé.
  - Données manquantes: Si présentes, indiqueront que l'IDH pour l'année 2021 n'est pas disponible pour ce pays.

- **gnipc_1990** (Revenu National Brut par habitant en 1990)
  - Description: Cette variable indique le Revenu National Brut (RNB) par habitant pour l'année 1990.
  - Unité de mesure: Le RNB par habitant est généralement exprimé en dollars américains ($) constants pour une comparaison internationale.
  - Données manquantes: Si présentes, indiqueront que le RNB par habitant pour l'année 1990 n'est pas disponible pour ce pays.

## Questions de Recherche

1. **Quels sont les pays qui ont connu la plus forte croissance de leur IDH de 2000 à 2021?**
   - Description : Cette question explore les pays qui ont réalisé les plus grandes améliorations dans leur développement humain au cours du 21e siècle.
   - Analyse : Calculer la croissance de l'IDH pour chaque pays entre 2000 et 2021 et identifier ceux avec la plus forte croissance.
   - Variables Utilisées : `hdi_2000`, `hdi_2021`.

2. **Quelles sont les régions qui ont connu la plus forte croissance de l'IDH au 21e siècle?**

3. **Comment la distribution de l'espérance de vie (le_1990) varie-t-elle entre les différentes catégories d'IDH (hdicode)?**
   - Description : Cette question explore comment l'espérance de vie en 1990 varie en fonction de la catégorie de développement humain d'un pays.
   - Analyse : Utiliser des boxplots ou des diagrammes en barres pour comparer l'espérance de vie moyenne entre les différentes catégories d'IDH.

4. **Existe-t-il une corrélation entre le Revenu National Brut par habitant (gnipc_1990) et l'IDH (hdi_2021)?**
   - Description : Cette question examine la relation entre le revenu d'un pays en 1990 et son développement humain en 2021.
   - Analyse : Utiliser des outils statistiques pour analyser la corrélation entre `gnipc_1990` et `hdi_2021`.
   - Variables Utilisées : `gnipc_1990`, `hdi_2021`.
 
```{r}
 
library(ggplot2)
library(dplyr)

# Load the data
hdi_data <- read.csv('HDI.csv')

# Remplacement des abréviations des régions par leurs noms complets
hdi_data$region <- gsub("EAP", "East Asia and Pacific", hdi_data$region)
hdi_data$region <- gsub("ECA", "Europe and Central Asia", hdi_data$region)
hdi_data$region <- gsub("LAC", "Latin America & the Caribbean", hdi_data$region)
hdi_data$region <- gsub("MNA.", "Middle East and North Africa", hdi_data$region)
hdi_data$region <- gsub("SAR", "South Asia", hdi_data$region)
hdi_data$region <- gsub("SSA", "Sub-Saharan Africa", hdi_data$region)
hdi_data$region <- gsub("SA", "South Asia", hdi_data$region)
hdi_data$region <- gsub("AS", "Asia", hdi_data$region)

# Supprimer les lignes avec des valeurs manquantes dans les colonnes qualitatives
hdi_data <- hdi_data %>%
  filter(!is.na(hdicode) & hdicode != "" & !is.na(region) & region != "") 

# Calculate the HDI growth for each country from 2000 to 2021
hdi_data <- hdi_data %>%
  mutate(hdi_growth_2000_2021 = hdi_2021 - hdi_2000)

# Remove non-finite values in hdi_growth_2000_2021
hdi_data <- hdi_data %>%
  filter(is.finite(hdi_growth_2000_2021))

# Part 1: Countries with the Highest HDI Growth from 2000 to 2021

# Identify top countries with highest HDI growth
top_countries_hdi_growth <- hdi_data %>%
  arrange(desc(hdi_growth_2000_2021)) %>%
  select(country, hdi_2000, hdi_2021, hdi_growth_2000_2021) %>%
  head(10)

# Check the data to ensure it's correct
print(top_countries_hdi_growth)

# Diagramme en barres pour la distribution des catégories de l'IDH
ggplot(hdi_data, aes(x = hdicode)) +
  geom_bar(fill = "skyblue", color = "black", alpha = 0.7) +
  labs(title = "Distribution des Catégories de l'IDH", x = "Catégorie de l'IDH", y = "Nombre de Pays") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold")
  ) +
  geom_text(stat='count', aes(label=..count..), vjust=-0.5)

# Boxplot pour le RNB par habitant en 1990
ggplot(hdi_data, aes(y = gnipc_1990)) +
  geom_boxplot(fill = "lightgreen", color = "black", alpha = 0.7) +
  labs(title = "Boxplot du RNB par habitant en 1990", y = "RNB par habitant en 1990 ($)") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold")
  )


# Histogramme pour la distribution de l'IDH en 2021
ggplot(hdi_data, aes(x = hdi_2021)) +
  geom_histogram(binwidth = 0.05, fill = "steelblue", color = "black", alpha = 0.7) +
  labs(title = "Distribution de l'IDH en 2021", x = "IDH en 2021", y = "Nombre de Pays") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold")
  ) +
  geom_density(aes(y = ..density..), color = "red", size = 1, alpha = 0.7)



# Diagramme en barres pour les 10 pays ayant la plus forte croissance de l'IDH
ggplot(top_countries_hdi_growth, aes(x = reorder(country, hdi_growth_2000_2021), y = hdi_growth_2000_2021)) +
  geom_bar(stat = "identity", fill = "#2c7fb8", color = "black", alpha = 0.7) +
  coord_flip() +
  xlab("Pays") +
  ylab("Croissance de l'IDH (2000-2021)") +
  ggtitle("Top 10 des pays avec la plus forte croissance de l'IDH (2000-2021)") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 12),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold")
  ) +
  geom_text(aes(label=round(hdi_growth_2000_2021, 3)), hjust=1.1, color="white")

# Part 2: Regions with the Highest HDI Growth in the 21st Century

# Calculate the average HDI growth for each region
region_hdi_growth <- hdi_data %>%
  group_by(region) %>%
  summarize(
    hdi_2000_mean = mean(hdi_2000, na.rm = TRUE),
    hdi_2021_mean = mean(hdi_2021, na.rm = TRUE)
  ) %>%
  mutate(hdi_growth_2000_2021 = hdi_2021_mean - hdi_2000_mean) %>%
  arrange(desc(hdi_growth_2000_2021))

# Calculer la croissance moyenne de l'IDH pour chaque région
region_hdi_growth2 <- hdi_data %>%
  group_by(region) %>%
  summarize(
    hdi_growth_mean = mean(hdi_growth_2000_2021, na.rm = TRUE)
  )

# Enhanced box plot for HDI growth by region
ggplot(hdi_data, aes(x = reorder(region, hdi_growth_2000_2021), y = hdi_growth_2000_2021, fill = region)) +
  geom_boxplot(outlier.shape = 21, outlier.size = 2) +
  ylab("HDI Growth (2000-2021)") +
  xlab("Region") +
  ggtitle("HDI Growth by Region (2000-2021)") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
    axis.text = element_text(size = 12, face = "bold"),
    axis.title = element_text(size = 14, face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none",
    panel.grid.major = element_line(color = "grey80"),
    panel.grid.minor = element_line(color = "grey90")
  ) +
  scale_fill_brewer(palette = "Paired")


# Histogramme de la croissance moyenne de l'IDH par région
ggplot(region_hdi_growth2, aes(x = reorder(region, hdi_growth_mean), y = hdi_growth_mean)) +
  geom_bar(stat = "identity", fill = "skyblue", color = "black", alpha = 0.7) +
  coord_flip() +
  xlab("Région") +
  ylab("Croissance Moyenne de l'IDH (2000-2021)") +
  ggtitle("Croissance Moyenne de l'IDH par Région (2000-2021)") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold")
  ) +
  geom_text(aes(label=round(hdi_growth_mean, 3)), hjust=1.1, color="black")



# Résumé pour les  regions 
region_summary <- hdi_data %>%
  group_by(region) %>%
  summarize(count = n())

print(region_summary)

# Résumé statistiques pour la croissance de l'IDH 
hdi_growth_summary <- hdi_data %>%
  summarize(
    mean = mean(hdi_growth_2000_2021, na.rm = TRUE),
    variance = var(hdi_growth_2000_2021, na.rm = TRUE),
    sd = sd(hdi_growth_2000_2021, na.rm = TRUE)
  )

print(hdi_growth_summary)

# Histogram and QQ plot for HDI growth
ggplot(hdi_data, aes(x = hdi_growth_2000_2021)) +
  geom_histogram(aes(y = ..density..), bins = 30, fill = "#69b3a2", color = "black", alpha = 0.7) +
  geom_density(color = "blue", size = 1) +
  ggtitle("Histogram and Density Plot of HDI Growth (2000-2021)") +
  xlab("HDI Growth (2000-2021)") +
  ylab("Density") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold")
  )

# QQ plot
ggplot(hdi_data, aes(sample = hdi_growth_2000_2021)) +
  stat_qq() +
  stat_qq_line() +
  ggtitle("QQ Plot of HDI Growth (2000-2021)") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold")
  )

# Shapiro-Wilk test for normality
shapiro_test <- shapiro.test(hdi_data$hdi_growth_2000_2021)
print(shapiro_test)


# Confidence interval for the mean of HDI growth
hdi_growth_mean <- mean(hdi_data$hdi_growth_2000_2021, na.rm = TRUE)
hdi_growth_sd <- sd(hdi_data$hdi_growth_2000_2021, na.rm = TRUE)
n <- nrow(hdi_data)

alpha <- 0.05
error_margin <- qt(1 - alpha/2, df = n - 1) * hdi_growth_sd / sqrt(n)
ci_lower <- hdi_growth_mean - error_margin
ci_upper <- hdi_growth_mean + error_margin

cat("95% Confidence Interval for the mean of HDI Growth (2000-2021): [", ci_lower, ", ", ci_upper, "]\n")

# Proportion des pays de la région  Sub-Saharan Africa
prop_ssa <- sum(hdi_data$region == "Sub-Saharan Africa") / nrow(hdi_data)

# Interval de confiance pour la région Sub-Saharan Africa
prop_ci <- prop.test(sum(hdi_data$region == "Sub-Saharan Africa"), nrow(hdi_data), conf.level = 0.95)
print(prop_ci)


# Boxplot pour l'espérance de vie en 1990 par catégorie d'IDH
ggplot(hdi_data, aes(x = hdicode, y = le_1990, fill = hdicode)) +
  geom_boxplot() +
  labs(title = "Distribution de l'espérance de vie en 1990 par catégorie d'IDH", 
       x = "Catégorie de l'IDH", 
       y = "Espérance de vie en 1990 (années)") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold"),
    legend.position = "none"
  ) +
  scale_fill_brewer(palette = "Set3")

# Calculer l'espérance de vie moyenne en 1990 par catégorie d'IDH
life_expectancy_summary <- hdi_data %>%
  group_by(hdicode) %>%
  summarize(mean_le_1990 = mean(le_1990, na.rm = TRUE))

# Diagramme en barres pour l'espérance de vie moyenne en 1990 par catégorie d'IDH
ggplot(life_expectancy_summary, aes(x = reorder(hdicode, mean_le_1990), y = mean_le_1990, fill = hdicode)) +
  geom_bar(stat = "identity", color = "black", alpha = 0.7) +
  labs(title = "Espérance de vie moyenne en 1990 par catégorie d'IDH", 
       x = "Catégorie de l'IDH", 
       y = "Espérance de vie moyenne en 1990 (années)") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold"),
    legend.position = "none"
  ) +
  scale_fill_brewer(palette = "Set3") +
  geom_text(aes(label=round(mean_le_1990, 1)), vjust=-0.5, color="black")


# Histogramme et QQ plot pour chaque catégorie d'IDH
ggplot(hdi_data, aes(x = le_1990)) +
  geom_histogram(aes(y = ..density..), bins = 30, fill = "#69b3a2", color = "black", alpha = 0.7) +
  facet_wrap(~hdicode) +
  geom_density(color = "blue", size = 1) +
  ggtitle("Histogramme et densité de l'espérance de vie en 1990 par catégorie d'IDH") +
  xlab("Espérance de vie en 1990 (années)") +
  ylab("Densité") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold")
  )

ggplot(hdi_data, aes(sample = le_1990)) +
  stat_qq() +
  stat_qq_line() +
  facet_wrap(~hdicode) +
  ggtitle("QQ Plot de l'espérance de vie en 1990 par catégorie d'IDH") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold")
  )

# Test de Shapiro-Wilk pour chaque catégorie d'IDH
shapiro_tests <- hdi_data %>%
  group_by(hdicode) %>%
  summarize(p_value = shapiro.test(le_1990)$p.value)

print(shapiro_tests)

# 2. Estimateurs de moyenne et de variance

# Moyenne et variance pour chaque catégorie d'IDH
summary_stats <- hdi_data %>%
  group_by(hdicode) %>%
  summarize(
    mean_le_1990 = mean(le_1990, na.rm = TRUE),
    var_le_1990 = var(le_1990, na.rm = TRUE),
    sd_le_1990 = sd(le_1990, na.rm = TRUE)
  )

print(summary_stats)

# 3. Intervalles de confiance des moyennes

# Calcul des intervalles de confiance pour la moyenne de l'espérance de vie en 1990 par catégorie d'IDH
ci_stats <- hdi_data %>%
  group_by(hdicode) %>%
  summarize(
    mean_le_1990 = mean(le_1990, na.rm = TRUE),
    sd_le_1990 = sd(le_1990, na.rm = TRUE),
    n = n()
  ) %>%
  mutate(
    error_margin = qt(1 - 0.05/2, df = n - 1) * sd_le_1990 / sqrt(n),
    ci_lower = mean_le_1990 - error_margin,
    ci_upper = mean_le_1990 + error_margin
  )

print(ci_stats)

# 4. Calcul d’intervalle de confiance d’une proportion pertinente

# Proportion des pays en Sub-Saharan Africa dans chaque catégorie d'IDH
prop_ssa <- hdi_data %>%
  filter(region == "Sub-Saharan Africa") %>%
  group_by(hdicode) %>%
  summarize(proportion = n() / sum(hdi_data$hdicode == hdicode))

# Calcul des intervalles de confiance pour la proportion
prop_ci <- hdi_data %>%
  filter(region == "Sub-Saharan Africa") %>%
  group_by(hdicode) %>%
  summarize(
    n = n(),
    N = sum(hdi_data$hdicode == hdicode)
  ) %>%
  mutate(
    proportion = n / N,
    error_margin = qt(1 - 0.05/2, df = N - 1) * sqrt((proportion * (1 - proportion)) / N),
    ci_lower = proportion - error_margin,
    ci_upper = proportion + error_margin
  )

print(prop_ci)

# 1. Diagramme de dispersion pour visualiser la relation entre hdi_growth_2000_2021 et le_2021
ggplot(hdi_data, aes(x = hdi_growth_2000_2021, y = le_2021)) +
  geom_point(color = "#69b3a2", alpha = 0.7) +
  geom_smooth(method = "lm", se = FALSE, color = "blue", linetype = "dashed") +
  labs(title = "Relation entre la croissance de l'IDH (2000-2021) et l'espérance de vie en 2021", 
       x = "Croissance de l'IDH (2000-2021)", 
       y = "Espérance de vie en 2021 (années)") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 11),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold")
  )

# 2. Calculer le coefficient de corrélation de Pearson
correlation <- cor(hdi_data$hdi_growth_2000_2021, hdi_data$le_2021, use = "complete.obs")
cat("Le coefficient de corrélation de Pearson entre hdi_growth_2000_2021 et le_2021 est :", correlation, "\n")

# 3. Test de significativité de la corrélation
cor_test <- cor.test(hdi_data$hdi_growth_2000_2021, hdi_data$le_2021)
print(cor_test)






#4a

# Histogramme pour l'IDH 2021 par région
ggplot(hdi_data, aes(x = hdi_2021, fill = region)) +
  geom_histogram(binwidth = 0.05, position = "dodge", alpha = 0.7, color = "black") +
  labs(title = "Histogramme de l'IDH 2021 par région", 
       x = "IDH 2021", 
       y = "Nombre de Pays") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold"),
    legend.position = "right"
  ) +
  scale_fill_brewer(palette = "Set3")

# Boxplot pour l'IDH 2021 par région
# Calcul des médianes pour annotation
medians <- hdi_data %>%
  group_by(region) %>%
  summarize(median_hdi_2021 = median(hdi_2021, na.rm = TRUE))

ggplot(hdi_data, aes(x = region, y = hdi_2021, fill = region)) +
  geom_boxplot(outlier.color = "red", outlier.shape = 8, outlier.size = 2, alpha = 0.7) +
  geom_jitter(width = 0.2, alpha = 0.5) +
  labs(title = "Boxplot de l'IDH 2021 par région", 
       x = "Région", 
       y = "IDH 2021") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14, face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_brewer(palette = "Set3") +
  geom_text(data = medians, aes(label = round(median_hdi_2021, 2), y = median_hdi_2021 + 0.02), color = "black", size = 3, vjust = -0.5)

#Interprétation
# Résumés statistiques :

# Fournissent la moyenne et l'écart type de l'IDH 2021 pour chaque région.
# Histogrammes et boxplots :

# Les histogrammes montrent la distribution de l'IDH 2021 par région.
# Les boxplots permettent de visualiser les différences de médiane et de variance de l'IDH 2021 entre les régions.
# Rapport de corrélation (Eta squared) :

# Le rapport de corrélation quantifie la proportion de la variance de l'IDH 2021 expliquée par la région. Un Eta squared proche # de 1 indique une forte association.
# Test d'égalité des moyennes (ANOVA) :

# Hypothèses :
# H0 (hypothèse nulle) : Les moyennes de l'IDH 2021 sont égales entre les différentes régions.
# H1 (hypothèse alternative) : Au moins une des moyennes de l'IDH 2021 est différente entre les régions.
# Conclusion : Si la p-value est inférieure à 0.05, on rejette l'hypothèse nulle et on conclut que les moyennes de l'IDH 2021 # sont significativement différentes entre les régions.


# Calculer le modèle ANOVA
model <- aov(hdi_2021 ~ region, data = hdi_data)

# Calculer Eta squared
ss_total <- sum(anova(model)$"Sum Sq")
ss_explained <- anova(model)$"Sum Sq"[1]
eta_squared <- ss_explained / ss_total
cat("Eta squared pour l'IDH 2021 par région est :", eta_squared, "\n")

# Test d'égalité des moyennes (ANOVA)
anova_result <- anova(model)
print(anova_result)


#4B

# Créer un tableau de contingence
contingency_table <- table(hdi_data$region, hdi_data$hdicode)
contingency_df <- as.data.frame(contingency_table)
colnames(contingency_df) <- c("Région", "Catégorie_IDH", "Fréquence")

# Représentation graphique du tableau de contingence avec un heatmap
# Représentation graphique du tableau de contingence avec un heatmap amélioré
ggplot(contingency_df, aes(Région, Catégorie_IDH, fill = Fréquence)) +
  geom_tile(color = "white") +
  geom_text(aes(label = Fréquence), color = "black", size = 4) +
  scale_fill_gradient(low = "white", high = "steelblue") +
  labs(title = "Heatmap du Tableau de Contingence entre Région et Catégorie d'IDH", 
       x = "Région", 
       y = "Catégorie d'IDH",
       fill = "Fréquence") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 14),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 14, face = "bold"),
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 10)
  )

# Test du chi-carré d'indépendance
chi2_test <- chisq.test(contingency_table)

# Afficher les résultats du test du chi-carré
print(chi2_test)

# Interprétation
if(chi2_test$p.value < 0.05) {
  cat("Les variables 'region' et 'hdicode' sont statistiquement dépendantes (p-value <", chi2_test$p.value, ").\n")
} else {
  cat("Les variables 'region' et 'hdicode' sont statistiquement indépendantes (p-value =", chi2_test$p.value, ").\n")
}

#Interprétation
#Tableau de contingence :

#Le tableau de contingence montre le nombre de pays dans chaque combinaison de region et hdicode.
#La représentation graphique en heatmap visualise ces fréquences de manière intuitive.
#Test d'indépendance (Chi-carré) :

#Hypothèses :
#H0 (hypothèse nulle) : Les variables region et hdicode sont indépendantes.
#H1 (hypothèse alternative) : Les variables region et hdicode sont dépendantes.
#Conclusion :
#Si la p-value est inférieure à 0.05, on rejette l'hypothèse nulle et on conclut que les variables region et hdicode sont #statistiquement dépendantes.
#Si la p-value est supérieure à 0.05, on ne peut pas rejeter l'hypothèse nulle et on conclut que les variables sont #indépendantes.





#4c
# Tracer le nuage de points et la droite des moindres carrés
ggplot(hdi_data, aes(x = gnipc_2021, y = hdi_2021)) +
  geom_point(color = "#69b3a2", alpha = 0.7) +
  geom_smooth(method = "lm", se = FALSE, color = "blue", linetype = "dashed") +
  labs(title = "Nuage de points et droite des moindres carrés entre RNB par habitant en 2021 et IDH en 2021", 
       x = "RNB par habitant en 2021 ($)", 
       y = "IDH en 2021") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 10),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold")
  )

# Calculer le coefficient de corrélation linéaire
correlation <- cor(hdi_data$gnipc_2021, hdi_data$hdi_2021, use = "complete.obs")
cat("Le coefficient de corrélation linéaire entre gnipc_2021 et hdi_2021 est :", correlation, "\n")

# Ajuster le modèle de régression linéaire
model <- lm(hdi_2021 ~ gnipc_2021, data = hdi_data)

# Résumé du modèle de régression
summary_model <- summary(model)
print(summary_model)

# Interprétation
if(summary_model$coefficients[2, 4] < 0.05) {
  cat("Le coefficient de régression est statistiquement significatif (p-value <", summary_model$coefficients[2, 4], ").\n")
} else {
  cat("Le coefficient de régression n'est pas statistiquement significatif (p-value =", summary_model$coefficients[2, 4], ").\n")
}

# Afficher les résidus du modèle
plot(model, which = 1)

# Tester l'hypothèse de normalité des résidus avec le test de Shapiro-Wilk
shapiro_test <- shapiro.test(residuals(model))
print(shapiro_test)

# Interprétation
# Nuage de points et droite des moindres carrés :

# Visualise la relation entre le RNB par habitant en 2021 et l'IDH en 2021.
# La droite des moindres carrés montre la tendance générale.
# Coefficient de corrélation linéaire :

# Le coefficient de corrélation de Pearson quantifie la force et la direction de la relation linéaire entre les deux variables. # Un coefficient proche de 1 ou -1 indique une forte corrélation, tandis qu'un coefficient proche de 0 indique une faible # corrélation.
# Pertinence de la régression linéaire :

# Résumé du modèle : Fournit des informations sur le modèle ajusté, y compris le coefficient de régression et sa significativité.
# Test de significativité : Si la p-value est inférieure à 0.05, le coefficient de régression est statistiquement significatif, # ce qui indique une relation linéaire significative entre les deux variables.
# Normalité des résidus : Le test de Shapiro-Wilk vérifie si les résidus de la régression suivent une distribution normale, ce # qui est une hypothèse clé de la régression linéaire




#D'autre variable
# Tracer le nuage de points et la droite des moindres carrés
ggplot(hdi_data, aes(x = le_1990, y = hdi_2021)) +
  geom_point(color = "#69b3a2", alpha = 0.7) +
  geom_smooth(method = "lm", se = FALSE, color = "blue", linetype = "dashed") +
  labs(title = "Nuage de points et droite des moindres carrés entre l'espérance de vie en 1990 et l'IDH en 2021", 
       x = "Espérance de vie en 1990 (années)", 
       y = "IDH en 2021") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 10),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold")
  )

# Calculer le coefficient de corrélation linéaire
correlation <- cor(hdi_data$le_1990, hdi_data$hdi_2021, use = "complete.obs")
cat("Le coefficient de corrélation linéaire entre le_1990 et hdi_2021 est :", correlation, "\n")


# Ajuster le modèle de régression linéaire
model <- lm(hdi_2021 ~ le_1990, data = hdi_data)

# Résumé du modèle de régression
summary_model <- summary(model)
print(summary_model)

# Interprétation de la significativité
if(summary_model$coefficients[2, 4] < 0.05) {
  cat("Le coefficient de régression est statistiquement significatif (p-value <", summary_model$coefficients[2, 4], ").\n")
} else {
  cat("Le coefficient de régression n'est pas statistiquement significatif (p-value =", summary_model$coefficients[2, 4], ").\n")
}

# Tester l'hypothèse de normalité des résidus avec le test de Shapiro-Wilk
shapiro_test <- shapiro.test(residuals(model))
print(shapiro_test)

# Graphiques de diagnostic de la régression linéaire
par(mfrow = c(2, 2)) # 2x2 grid of plots
plot(model)


#Interprétation des résultats
#Nuage de points et droite des moindres carrés :

#Visualise la relation entre l'espérance de vie en 1990 et l'IDH en 2021.
#La droite des moindres carrés montre la tendance générale.
#Coefficient de corrélation linéaire :

#Le coefficient de corrélation de Pearson quantifie la force et la direction de la relation linéaire entre les deux variables.
#Pertinence de la régression linéaire :

#Résumé du modèle : Fournit des informations sur le modèle ajusté, y compris le coefficient de régression et sa significativité.
#Test de significativité : Si la p-value est inférieure à 0.05, le coefficient de régression est statistiquement significatif.
#Normalité des résidus : Le test de Shapiro-Wilk vérifie si les résidus de la régression suivent une distribution normale.

```